version: 2.1

jobs:
  build:
    description: Building the code
    docker:
      - image: cimg/node:16.16.0 # the primary container, where your job's commands are run
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run the build
          command: npm run build

  test:
    description: Testing the code
    docker:
      - image: circleci/node:latest
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Test the code
          command: npm run testCode

workflows:
  my-workflow:
    jobs:
      - build
      - test
